/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	boosv1alpha1 "github.com/mattmoor/boo-maps/pkg/apis/boos/v1alpha1"
	versioned "github.com/mattmoor/boo-maps/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mattmoor/boo-maps/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mattmoor/boo-maps/pkg/client/listers/boos/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MutableMapInformer provides access to a shared informer and lister for
// MutableMaps.
type MutableMapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MutableMapLister
}

type mutableMapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMutableMapInformer constructs a new informer for MutableMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMutableMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMutableMapInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMutableMapInformer constructs a new informer for MutableMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMutableMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BoosV1alpha1().MutableMaps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BoosV1alpha1().MutableMaps(namespace).Watch(options)
			},
		},
		&boosv1alpha1.MutableMap{},
		resyncPeriod,
		indexers,
	)
}

func (f *mutableMapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMutableMapInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mutableMapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&boosv1alpha1.MutableMap{}, f.defaultInformer)
}

func (f *mutableMapInformer) Lister() v1alpha1.MutableMapLister {
	return v1alpha1.NewMutableMapLister(f.Informer().GetIndexer())
}
