/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/mattmoor/boo-maps/pkg/apis/boos/v1alpha1"
	scheme "github.com/mattmoor/boo-maps/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImmutableMapsGetter has a method to return a ImmutableMapInterface.
// A group's client should implement this interface.
type ImmutableMapsGetter interface {
	ImmutableMaps(namespace string) ImmutableMapInterface
}

// ImmutableMapInterface has methods to work with ImmutableMap resources.
type ImmutableMapInterface interface {
	Create(*v1alpha1.ImmutableMap) (*v1alpha1.ImmutableMap, error)
	Update(*v1alpha1.ImmutableMap) (*v1alpha1.ImmutableMap, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ImmutableMap, error)
	List(opts v1.ListOptions) (*v1alpha1.ImmutableMapList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImmutableMap, err error)
	ImmutableMapExpansion
}

// immutableMaps implements ImmutableMapInterface
type immutableMaps struct {
	client rest.Interface
	ns     string
}

// newImmutableMaps returns a ImmutableMaps
func newImmutableMaps(c *BoosV1alpha1Client, namespace string) *immutableMaps {
	return &immutableMaps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the immutableMap, and returns the corresponding immutableMap object, and an error if there is any.
func (c *immutableMaps) Get(name string, options v1.GetOptions) (result *v1alpha1.ImmutableMap, err error) {
	result = &v1alpha1.ImmutableMap{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("immutablemaps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImmutableMaps that match those selectors.
func (c *immutableMaps) List(opts v1.ListOptions) (result *v1alpha1.ImmutableMapList, err error) {
	result = &v1alpha1.ImmutableMapList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("immutablemaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested immutableMaps.
func (c *immutableMaps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("immutablemaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a immutableMap and creates it.  Returns the server's representation of the immutableMap, and an error, if there is any.
func (c *immutableMaps) Create(immutableMap *v1alpha1.ImmutableMap) (result *v1alpha1.ImmutableMap, err error) {
	result = &v1alpha1.ImmutableMap{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("immutablemaps").
		Body(immutableMap).
		Do().
		Into(result)
	return
}

// Update takes the representation of a immutableMap and updates it. Returns the server's representation of the immutableMap, and an error, if there is any.
func (c *immutableMaps) Update(immutableMap *v1alpha1.ImmutableMap) (result *v1alpha1.ImmutableMap, err error) {
	result = &v1alpha1.ImmutableMap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("immutablemaps").
		Name(immutableMap.Name).
		Body(immutableMap).
		Do().
		Into(result)
	return
}

// Delete takes name of the immutableMap and deletes it. Returns an error if one occurs.
func (c *immutableMaps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("immutablemaps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *immutableMaps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("immutablemaps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched immutableMap.
func (c *immutableMaps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImmutableMap, err error) {
	result = &v1alpha1.ImmutableMap{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("immutablemaps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
