/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/mattmoor/boo-maps/pkg/apis/boos/v1alpha1"
	scheme "github.com/mattmoor/boo-maps/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WithPodsGetter has a method to return a WithPodInterface.
// A group's client should implement this interface.
type WithPodsGetter interface {
	WithPods(namespace string) WithPodInterface
}

// WithPodInterface has methods to work with WithPod resources.
type WithPodInterface interface {
	Create(*v1alpha1.WithPod) (*v1alpha1.WithPod, error)
	Update(*v1alpha1.WithPod) (*v1alpha1.WithPod, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.WithPod, error)
	List(opts v1.ListOptions) (*v1alpha1.WithPodList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WithPod, err error)
	WithPodExpansion
}

// withPods implements WithPodInterface
type withPods struct {
	client rest.Interface
	ns     string
}

// newWithPods returns a WithPods
func newWithPods(c *BoosV1alpha1Client, namespace string) *withPods {
	return &withPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the withPod, and returns the corresponding withPod object, and an error if there is any.
func (c *withPods) Get(name string, options v1.GetOptions) (result *v1alpha1.WithPod, err error) {
	result = &v1alpha1.WithPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("withpods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WithPods that match those selectors.
func (c *withPods) List(opts v1.ListOptions) (result *v1alpha1.WithPodList, err error) {
	result = &v1alpha1.WithPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("withpods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested withPods.
func (c *withPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("withpods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a withPod and creates it.  Returns the server's representation of the withPod, and an error, if there is any.
func (c *withPods) Create(withPod *v1alpha1.WithPod) (result *v1alpha1.WithPod, err error) {
	result = &v1alpha1.WithPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("withpods").
		Body(withPod).
		Do().
		Into(result)
	return
}

// Update takes the representation of a withPod and updates it. Returns the server's representation of the withPod, and an error, if there is any.
func (c *withPods) Update(withPod *v1alpha1.WithPod) (result *v1alpha1.WithPod, err error) {
	result = &v1alpha1.WithPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("withpods").
		Name(withPod.Name).
		Body(withPod).
		Do().
		Into(result)
	return
}

// Delete takes name of the withPod and deletes it. Returns an error if one occurs.
func (c *withPods) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("withpods").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *withPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("withpods").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched withPod.
func (c *withPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WithPod, err error) {
	result = &v1alpha1.WithPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("withpods").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
