/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ImmutableMapListerExpansion allows custom methods to be added to
// ImmutableMapLister.
type ImmutableMapListerExpansion interface{}

// ImmutableMapNamespaceListerExpansion allows custom methods to be added to
// ImmutableMapNamespaceLister.
type ImmutableMapNamespaceListerExpansion interface{}

// MutableMapListerExpansion allows custom methods to be added to
// MutableMapLister.
type MutableMapListerExpansion interface{}

// MutableMapNamespaceListerExpansion allows custom methods to be added to
// MutableMapNamespaceLister.
type MutableMapNamespaceListerExpansion interface{}

// WithPodListerExpansion allows custom methods to be added to
// WithPodLister.
type WithPodListerExpansion interface{}

// WithPodNamespaceListerExpansion allows custom methods to be added to
// WithPodNamespaceLister.
type WithPodNamespaceListerExpansion interface{}
