/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mattmoor/boo-maps/pkg/apis/boos/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMutableMaps implements MutableMapInterface
type FakeMutableMaps struct {
	Fake *FakeBoosV1alpha1
	ns   string
}

var mutablemapsResource = schema.GroupVersionResource{Group: "boos.mattmoor.io", Version: "v1alpha1", Resource: "mutablemaps"}

var mutablemapsKind = schema.GroupVersionKind{Group: "boos.mattmoor.io", Version: "v1alpha1", Kind: "MutableMap"}

// Get takes name of the mutableMap, and returns the corresponding mutableMap object, and an error if there is any.
func (c *FakeMutableMaps) Get(name string, options v1.GetOptions) (result *v1alpha1.MutableMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mutablemapsResource, c.ns, name), &v1alpha1.MutableMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutableMap), err
}

// List takes label and field selectors, and returns the list of MutableMaps that match those selectors.
func (c *FakeMutableMaps) List(opts v1.ListOptions) (result *v1alpha1.MutableMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mutablemapsResource, mutablemapsKind, c.ns, opts), &v1alpha1.MutableMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MutableMapList{ListMeta: obj.(*v1alpha1.MutableMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.MutableMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mutableMaps.
func (c *FakeMutableMaps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mutablemapsResource, c.ns, opts))

}

// Create takes the representation of a mutableMap and creates it.  Returns the server's representation of the mutableMap, and an error, if there is any.
func (c *FakeMutableMaps) Create(mutableMap *v1alpha1.MutableMap) (result *v1alpha1.MutableMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mutablemapsResource, c.ns, mutableMap), &v1alpha1.MutableMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutableMap), err
}

// Update takes the representation of a mutableMap and updates it. Returns the server's representation of the mutableMap, and an error, if there is any.
func (c *FakeMutableMaps) Update(mutableMap *v1alpha1.MutableMap) (result *v1alpha1.MutableMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mutablemapsResource, c.ns, mutableMap), &v1alpha1.MutableMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutableMap), err
}

// Delete takes name of the mutableMap and deletes it. Returns an error if one occurs.
func (c *FakeMutableMaps) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mutablemapsResource, c.ns, name), &v1alpha1.MutableMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMutableMaps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mutablemapsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MutableMapList{})
	return err
}

// Patch applies the patch and returns the patched mutableMap.
func (c *FakeMutableMaps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MutableMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mutablemapsResource, c.ns, name, data, subresources...), &v1alpha1.MutableMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutableMap), err
}
