/*
Copyright 2019 Matt Moore

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mattmoor/boo-maps/pkg/apis/boos/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWithPods implements WithPodInterface
type FakeWithPods struct {
	Fake *FakeBoosV1alpha1
	ns   string
}

var withpodsResource = schema.GroupVersionResource{Group: "boos.mattmoor.io", Version: "v1alpha1", Resource: "withpods"}

var withpodsKind = schema.GroupVersionKind{Group: "boos.mattmoor.io", Version: "v1alpha1", Kind: "WithPod"}

// Get takes name of the withPod, and returns the corresponding withPod object, and an error if there is any.
func (c *FakeWithPods) Get(name string, options v1.GetOptions) (result *v1alpha1.WithPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(withpodsResource, c.ns, name), &v1alpha1.WithPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WithPod), err
}

// List takes label and field selectors, and returns the list of WithPods that match those selectors.
func (c *FakeWithPods) List(opts v1.ListOptions) (result *v1alpha1.WithPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(withpodsResource, withpodsKind, c.ns, opts), &v1alpha1.WithPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WithPodList{ListMeta: obj.(*v1alpha1.WithPodList).ListMeta}
	for _, item := range obj.(*v1alpha1.WithPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested withPods.
func (c *FakeWithPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(withpodsResource, c.ns, opts))

}

// Create takes the representation of a withPod and creates it.  Returns the server's representation of the withPod, and an error, if there is any.
func (c *FakeWithPods) Create(withPod *v1alpha1.WithPod) (result *v1alpha1.WithPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(withpodsResource, c.ns, withPod), &v1alpha1.WithPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WithPod), err
}

// Update takes the representation of a withPod and updates it. Returns the server's representation of the withPod, and an error, if there is any.
func (c *FakeWithPods) Update(withPod *v1alpha1.WithPod) (result *v1alpha1.WithPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(withpodsResource, c.ns, withPod), &v1alpha1.WithPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WithPod), err
}

// Delete takes name of the withPod and deletes it. Returns an error if one occurs.
func (c *FakeWithPods) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(withpodsResource, c.ns, name), &v1alpha1.WithPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWithPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(withpodsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WithPodList{})
	return err
}

// Patch applies the patch and returns the patched withPod.
func (c *FakeWithPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WithPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(withpodsResource, c.ns, name, data, subresources...), &v1alpha1.WithPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WithPod), err
}
